### ISSUE TITLE
Update pythonX_path fixtures for ubuntu 20.04

### ISSUE THREAD

**Issue by ManInFez** [equinor/komodoenv#33]
python 3.6 is no longer shipped with ubuntu-latest (20.04) but comes with python 3.8. The github workflow should be adjusted accordingly. In addition the fixture for getting the python executable is no longer working, as python 3.6 is no longer installed in /usr/bin

**Comment by dotfloat** [comment]
I think this should be closed as WONTFIX:

`komodoenv` is only meant to run in the same environment as our deployed komodo releases, which is to say RHEL 7 on Equinor machines. CentOS 7 is the close enough that I do testing on it. `komodoenv` is forward-compatible with RHEL 8 to some extent, but that's only because it was relatively trivial to do.

The testing suite supports Ubuntu only due to Github Actions, which only has that distro. Ubuntu 18.04 is EOL by April 2023, while CentOS 7 is EOL by June 2024. We can either start using the CentOS 7 docker image or install Python 3.6 into Ubuntu 22.04 when the time comes. I would rather not do either of these things now because using docker or installing software makes the CI slower.

**Comment by sondreso** [comment]
Sounds like a good reason to not fix now, closing this :slightly_smiling_face:
